AWSTemplateFormatVersion: 2010-09-09 # cfn {Cloudformation Snippets}
Description: |
  Cloudformation template that creates an s3 bucket static website hosting enabled, cloudfront distribution and a route 53 record set to deploy a static website {KittensCarousel}
Parameters:
  DomainName: # parameter-type-hostedzone-id
    Description: Need to  choose your hosted zone.
    Type: AWS::Route53::HostedZone::Id
  KittensSubDomain:  # examples kittens.clarusway.com | kittens.domain.us (anySCharacter).(AnySCharacter) (regex)
    Description: Please Write a valid subdomain.
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
Resources:
  KittensBucket: # s3-bucket
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref KittensSubDomain
      WebsiteConfiguration:
        IndexDocument: index.html
